### ISSUE TITLE
1) create Eid mubarak post for TL shades and Chello  & Eser

### ISSUE THREAD

**Issue by MalshaGamage** [gayandusmantha/sprint-dsquare#126]

**Comment by Prasadi7** [comment]
Done.
![Al-Hajj-Mubarak (2).jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5993c8e23d9d09001a319e9a/125516c66e82c728ace21e0d46c998d70b8389a3c2c4aa41a54ff19f690e753a6b48e13b628ae92dbc56395b4d5a47ab44505644faf8dd28a1b23d708a5e02ecd86b0a76932f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e48f864c3c18011c80fc5527ed.jpg)
![Al-Hajj-Mubarak-02.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5993c8e23d9d09001a319e9a/125516c66e82c728ace21e0d46c998d70b8389a3c2c4aa41a54ff19f641675316546b3397f8fe62bab0021435a5649a949515f42fdad8a2ca2b73c7088550ae4d7385d21d42103eee9dc4be05ce36ade0d97bcae884ecae93826e3828c4d381b061e81fb4f78.jpg)
![Al-Hajj-Mubarak.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5993c8e23d9d09001a319e9a/125516c66e82c728ace21e0d46c998d70b8389a3c2c4aa41a54ff19f6b0a65633b0ba92e7391a172fd1722565a5747ac47590b47fbfd882ba6b43571835a5eef847f4366846c4ff8e7df46f554f832815d84b1b68b49c3ec3426e58d894e371c060ac4.jpg)
![Al Hajj Mubarak Post.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5993c8e23d9d09001a319e9a/125516c66e82c728ace21e0d46c998da0b8389a3cfc4aa41a54ff19f697628603d46ef696097ec22ba416f43554d4ba5465d574dfcff887fa5b138718a5c09e4d0645921c46803b0aac04ee155e57dd205d0f4ae805ec1ef3724e2888b463d1c03108af95c3db2d4.jpg)
