### ISSUE TITLE
Aqua Documentation V3

### ISSUE THREAD

**Issue by MalshaGamage** [gayandusmantha/sprint-dsquare#62]
3rd week August

**Comment by MalshaGamage** [comment]
sent for the Aqua team .(15/08/2018)

**Comment by Prasadi7** [comment]
Sent the finalize BRS for Stock managemet stage 1.

**Comment by MalshaGamage** [comment]
Get feedback from the Aqua team. (16/08/2018)

**Comment by MalshaGamage** [comment]
Meeting with AQUA team. (21/08/2018- 3.00pm)

**Comment by MalshaGamage** [comment]
Rearrange the document version 3
